### ISSUE TITLE
[server]web3 트랜잭션 이벤트리스너 작성

### ISSUE THREAD

**Issue by atoye1** [codestates-beb/beb-07-second-EWE#102]
### 0. 설계
다른 버츄어머신 또는 다른 프로세스에서 실행되도록 서버와 분리하여 설계한다.
(dockerization은 여유가 된다면 시도해본다.)
최초 블록이벤트를 db와 sync()하는 부분은 서버가 최초 구동시에도 실행가능하도록 컴포넌트화 한다.
구현상의 편의를 위해 express web서버 형태로 작성한다.
(http 요청을 통해 healthCheck가 가능하고, sync를 manually trigger 할 수 있도록 작성한다.)
서버는 최초 구동시, 그리고 setInterval로 eventListener에 sync()요청을 정기적으로 보낸다.

### 1. 최초 실행시나 trigger 시의 로직
- db에서 마지막으로 기록한 tx의 블록넘버를 조회한다.
- 현재 체인의 블록넘버가 마지막으로 기록한 블록넘버보다 높으면 현재 블록까지 모든 블록을 조회한다.
- 조회한 블록안에서 해당하는 CA에 대한 트랜잭션이 발생한 경우를 추출한다.
- 트랜잭션을 파싱해서 tx테이블에 삽입한다.
- 파싱한 트랜잭션중 db에 변경사항이 생기는 경우 db를 업데이트 한다.
- 
### 2. 데몬 실행중
- 2가지 컨트랙트의 이벤트를 리슨한다.
- 리슨하는 이벤트의 종류는 Transfer, Approval 두 가지 이다.
- 이더를 전달하는 트랜잭션의 경우 어떻게 필터링하지(?) : admin account 기준으로 필터링한다.
- Transfer event (토큰 지급, nft 민트, 유저간 nft 전송 모두 Transfer 이벤트가 발생된다.)
- Approval event 발행된 토큰과 nft에 대해서 발행 및 전송과 동시에 
  admin Account에 full approval을 주도록 스마트컨트랙트를 업데이트 한다.

**Comment by atoye1** [comment]
중간 공유를 해드리자면 오늘 밤까지는 구현이 완료될 듯 합니다.
다만 이벤트 리스너와 서버에 둘 다 있는 로직들을 제거하려면 클라이언트와 의논이 조금 필요합니다.

가장 문제가 될 수 있는 부분은 nft 민팅하는 부분 입니다.
POST 요청으로 mintNFT 할때, 해당 요청의 반환값으로 새롭게 생성된 nft객체를 전달해 드립니다.

민팅 요청 성공시, 현재는 아래와 같이 응답을 드립니다.
![image](https://user-images.githubusercontent.com/47937914/211779973-9273d5e4-fa31-40a4-8fbe-d4cfff77212b.png)

**위 응답을 아래와 같이 바꿔도 될까요?**
```
{
        status: 'ok',
        message: 'new nft created',
        tokenId: `${newTokenId}`,
}
```

(반환값을 클라이언트에서 실제로 활용을 하는지? 아니면 성공/실패만 판단하는지 궁금합니다.)

**Comment by Duhoon** [comment]
넵,  사실 현재까지는 이전의 응답에서 반환받고 있는 nft 객체를 이용하고 있지는 않고 있었습니다.

하지만 새로 생성된 NFT가 서버 데이터에 추가가 되는 동시에, 민팅이 끝난 클라이언트의 화면에서 NFT 리스트에 추가가되어져야 UX가 개선이 됩니다.
이를테면 민팅했는데, 클라이언트 화면에서 목록이 갱신되지 않으면, NFT가 추가되었는지 안되었는지 모르기 때문입니다.
그래서 이 UX를 개선시키려면 이전과 같은 방법이 더 유리하긴 합니다.

하지만 제가 생각했을 땐 이번 프로젝트는 거기까지 UX개선을 하진 못 할 것 같아서 바뀐 방식도 무리 없이 사용할 수 있을 것이라 생각합니다.
