### ISSUE TITLE
[client] Pagination 설계

### ISSUE THREAD

**Issue by Russ481-k** [codestates-beb/beb-07-second-EWE#107]
클라이언트에서 Pagination을 구현하기 위해 서버에 요구되는 것은 다음과 같습니다.

1. 해당 테이블의 총 길이 

2. offset 에서 limit에 해당하는 값을 가진 데이터 셋

클라이언트에서 요구하는 게시물 단위를 다음과 같이 쿼리로 보냅니다.

-posts
http://20.214.190.113:5050/posts/?offset={offset}&limit={limit}

-nfts
http://20.214.190.113:5050/nfts/?offset={offset}&limit={limit}

posts와 nft의 테이블의 총 길이와 

offset 에서 limit에 해당하는 값을 가진 데이터 셋을  다음과 같이 보내주시면 감사하겠습니다.

{
 posts: [{dataSet},{dataSet},{dataSet}]
 totalNum: 500
}

**Comment by Russ481-k** [comment]
페이지네이션 필터링 구현 중 기존 객체에서 다음과 같은 부분이 누락되어 포스트 컴포넌트로 출력하는 것에 어려움이 있습니다.

            "user": {
                "id": 2,
                "wallet_account": "0x914e6a93bA2e7B4192f772221E3bd3be42903984",
                "nickname": "test2 nickname"
            },
            "images": [
                {
                    "uri": "https://nodeauction.42msnsnsfoav6.ap-northeast-2.cs.amazonlightsail.com/images/2.jpg"
                }
            ]

이상의 요소을 다음과 같이 요청 했을 경우에 받게 될 객체에 추가해 주시면 감사하겠습니다!

posts/findposts/?search={검색어}&offset={offset}&limit={limit}

**Comment by hyuntae384** [comment]
수정하여 커밋하였습니다!
