### ISSUE TITLE
[server] AWS-SDK, multer-s3를 통한 이미지 업로드 구현

### ISSUE THREAD

**Issue by hyuntae384** [codestates-beb/beb-07-second-EWE#110]
1. AWS sign-up 후 s3 버킷 생성
2. multer-s3를 통한 AWS 버킷 연동
3. postman으로 POST 시 이미지 AWS로 업로드
4. API 수정

**Comment by atoye1** [comment]
다른 컴포넌트들과 잘 작동하는 것을 확인했으므로 이슈를 닫습니다.
