### ISSUE TITLE
[client] 인증 전략 클라이언트 구현

### ISSUE THREAD

**Issue by Duhoon** [codestates-beb/beb-07-second-EWE#116]
회원가입에서 로그인까지 클라이언트에서 서버로 요청하는 로직들을 구현해야합니다.

**Comment by Duhoon** [comment]
<img width="782" alt="스크린샷 2023-01-09 오전 1 36 28" src="https://user-images.githubusercontent.com/18072469/211208301-eb9b19a0-dde5-4ed7-8991-d5edcccbfcf7.png">

현재 클라이언트 `http://localhost:3000`에서 `POST /users/login` 으로 email 값과 password 값을 바디에 포함하여 요청을 보낼 경우 위와 같은 에러가 발생하고 있습니다. refreshToken을 받아오기 위해 axios 설정 중 credentialWith를 true로 설정해줬기 때문인 것 같습니다. 이를 해결하기 위해서는 server cors 설정도 `http://localhost:3000`와 `http://ewe-client.s3-website.ap-northeast-2.amazonaws.com/`를 origin 에 "*" 로 처리 하지 않고 직접 작성해줘야할 필요가 있는 것 같습니다.

**Comment by Duhoon** [comment]
User가 로그인될 때 반환받는 데이터가 AccessToken 만이라면, 문제가 발생합니다. 지금과 같은 형태라면 로그인 성공한 유저가 테이블에서 어떤 ID값을 갖고 있는지 클라이언트가 확인할 방도가 없습니다.

로그인 되었을 때 반환하는 데이터에 적어도 유저의 ID값이 포함되게 해줘야할 것 같습니다.

**Comment by atoye1** [comment]
### cors는 해결됐는데 이후에 이런 에러가 뜨네요
![image](https://user-images.githubusercontent.com/47937914/211225833-d99852c4-aecb-474d-a836-2eaa01d260b6.png)

### ID 값을 확인하는 방법은
토큰 획득후 http://20.214.190.113:5050/users/my 여기에 요청하는 방법이 있는데
편의를 위해 일단 토큰발행시 다 전달해 드릴게요

**Comment by Duhoon** [comment]
넵, 위 문제는 아마 제가 id 반환까지 수정됐을 때를 가정해서 로그인 요청 이후 바로 유저정보를 요청하와서 생기는 문제은 것 같습니다.

/users/my API가 제공된다면 문제 없겠군요! 어떤 식으로 작동하는지 확인한 이후에 다시 이슈 공유하도록 하겠습니다.

**Comment by atoye1** [comment]
![image](https://user-images.githubusercontent.com/47937914/211226093-964fb976-7556-4a72-abb3-84ee10d35cea.png)
로그인 성공 후 응답이 이렇게 오도록 변경함.

**Comment by Duhoon** [comment]
`http://localhost:3000`에서 로그인 API를 이용하여 AccessToken과 User를 가져오는데는 성공하고 있지만, refreshToken cookie가 넘어오지 않고 있습니다. 포스트맨에서도 넘어오는 것은 확인되는 것으로 보아, cookie 설정을 확인해봐야할 것 같습니다.

**Comment by atoye1** [comment]
저녁에 시간되시면 화면공유로 같이 해결해볼까요?
