### ISSUE TITLE
[client] NFT 민팅 기능 제공

### ISSUE THREAD

**Issue by Duhoon** [codestates-beb/beb-07-second-EWE#131]
로그인 후 사용자가 NFT를 민팅할 수 있는 기능을 제공합니다.
이 기능을 통해서 서버와 연결된 체인에 NFT를 민팅하여 확인할 수 있습니다.

**Comment by Duhoon** [comment]
**[ POST 요청 419 status 반환 문제]**
<img width="782" alt="스크린샷 2023-01-10 오후 12 39 42" src="https://user-images.githubusercontent.com/18072469/211456898-c76e4781-709a-4443-82e3-40b8cece7bb7.png">

위에서 확인될 수 있는 문제를 확인해본 결과 보내주신 accessToken 데이터를 `Token ${accessToken}`의 형식으로 Authorization 헤더에 병기 하는 방식으로 해결하려고 합니다. 그래서 현재는 정상적으로 401 status 가 반환이 되고 있습니다.
서버 측에서 Authorization 헤더에 담아서 보내지는 accessToken 데이터를 한 번 파싱해서 검증해주실 수 있을지 제안드립니다.

**Comment by atoye1** [comment]
accessToken 검증 로직이 정상적으로 작동하는걸로 보이는데 그 이유는 token expired 에러가 발생했기 때문입니다.
accessToken이 expire된 응답을 받을시, 클라이언트에서 가지고 있는 refreshToken을 활용해서 accessToken을 재발급받아 사용하셔야 된다고 생각합니다.

**Comment by atoye1** [comment]
그런데 지금 api 서버 버전이 두개로 돌아가는데
어디에다 요청한건지 알려주시면 좋겠습니다.
기존 http인지 새로 배포한 https인지

**Comment by atoye1** [comment]
아 로그를 보니 기존에다 하셨군요
이제 모든 요청을 https에 해서 테스트해보셔야 디버깅이 의미있을것 같습니다.
api문서에 신규 엔드포인트 기재해놨습니다.

**Comment by Duhoon** [comment]
넵, 위 문제는 제 테스트 환경에서 accessToken의 발급 기간 1시간 이후에 요청을 드려서 생긴 문제라는 걸 확인한 것 같습니다.

사실 이외에 직접적으로 accessToken에 접근하는 시도를 한 번은 막고자 `Token` 이나 `Bearer` 문구를 붙여서 보내기는 하는데
이번에는 accessToken 만 보내는 방식으로 구현해보도록 하겠습니다.

**Comment by atoye1** [comment]
아 제가 질문을 좀 오해했나보네요

실제로 토큰 사용할때 Bearer 같은 접두어를 붙이는 거 알고 있는데 
생각하시는대로 편의상 그런 접두어 없이 토큰본문만 보내는 걸로 구현되어 있습니다.


이제 서버 재배포 절차가 조금은 까다로워져서 굳이 필수적으로 필요하지 않다면 
끝까지 미반영하고싶은데, 만약 꼭 필요하다면 회의시간에 말씀해주세요.

**Comment by Duhoon** [comment]
클라이언트에서 정상 작동 확인됐습니다. 기능 구현 완료되어서 이슈 닫겠습니다.
