### ISSUE TITLE
[client/server]refreshToken 발행후에도 새로고침시 로그인 풀림

### ISSUE THREAD

**Issue by atoye1** [codestates-beb/beb-07-second-EWE#132]
![Image](https://user-images.githubusercontent.com/47937914/211446087-145762cc-6701-4cd9-be54-9e220a8f1efe.png)

캡쳐화면과 같이 로그인시 refreshToken 쿠키가 정상적으로 전달되는 것은 확인했습니다.
다만 새로고침시 로그인이 풀리는 문제가 해결되지 않습니다.

**Comment by Duhoon** [comment]
여기서부터는 클라이언트에서 수정이 필요하겠네요. 확인했습니다.

**Comment by atoye1** [comment]
로컬환경에서 테스트해서 생긴 문제일수도 있겠지만 화면 첨부합니다.
최신버전 클라이언트에서도 api endpoint 수정후 테스트 바랍니다.

1. 로그인 직후 console 메시지
![image](https://user-images.githubusercontent.com/47937914/211446728-9031f8bf-0957-4777-a4f9-37a9d1ec7138.png)
2. 새로고침 후 console
![image](https://user-images.githubusercontent.com/47937914/211446820-dd817160-24bb-4410-8a5c-db1320755153.png)

**Comment by Duhoon** [comment]
<img width="782" alt="스크린샷 2023-01-10 오후 1 26 36" src="https://user-images.githubusercontent.com/18072469/211461965-b9b21199-e4b8-423e-95b1-e2edce812f5d.png">

현재 https 로 로그인 요청한 결과 인증은 되는데 refreshToken 이 여전히 발급이 안되고 있는 것 같습니다.

해당 API 요청 클라이언트 코드가 참고될 것 같아서 아래에 첨부합니다.

```js
const origin = "https://nodeauction.42msnsnsfoav6.ap-northeast-2.cs.amazonlightsail.com";
const loginURL = origin + "/users/login";

export const loginUser = async(userInfo)=>{
    if(!userInfo.email || !userInfo.password) return new Error("invalid info");

    const loginResult = await axios.post(loginURL, userInfo, {withCredentials:true})
    .then(result=>result.data)
    .catch(console.log);

    return loginResult;
}
```

**Comment by atoye1** [comment]
스크린샷에서 크롬 익스텐션으로 보내 주신 쿠키는 
클라이언트 http://ewe-client.s3-website.ap-northeast-2.amazonaws.com/에서 사용되는 쿠키를 조회한 것으로 보입니다.

우리가 서버에서 사용하는 쿠키는`nodeauction.42msnsnsfoav6.ap-northeast-2.cs.amazonlightsail.com` 도메인에서 사용하는 쿠키입니다. 이 때문에 해당 크롬 익스텐션에서 조회가 안되는 것으로 생각됩니다.


배포된 클라이언트에서도 아래 주의요함 부분을 클릭시 쿠키가 들어있는 것을 확인할 수 있습니다.
쿠키를 아래와 같은 방식으로 확인해 보고 답글 주세요
![image](https://user-images.githubusercontent.com/47937914/211466806-9a19fa84-a0b4-44cf-9ee8-ae58e42cf307.png)

![image](https://user-images.githubusercontent.com/47937914/211466676-8b4a6808-f4da-41c7-ace9-af00483a63b0.png)

**Comment by Duhoon** [comment]
확인했습니다. 이 주소로 발행된 쿠키로 새로고침 시 자동로그인되는 작업을 진행하도록 하겠습니다.

**Comment by Duhoon** [comment]
배포된 클라이언트에서도 재로그인 되는 것까지 확인을 마쳤습니다.
기능 구현 완료되어 본 이슈 닫도록 하겠습니다.
