### ISSUE TITLE
[client] 클라이언트 배포 서버 .env 관련 해결방안

### ISSUE THREAD

**Issue by Duhoon** [codestates-beb/beb-07-second-EWE#143]
현재 Local 환경에서는 구글맵 API 키를 클라이언트 `.env` 파일에서 사용을 하고 있습니다.
GitAction을 이용하여 `build`된 어플리케이션을 배포하고 있기 때문에
배포 환경에서도 구글맵을 이용하여 사용자에게 기능을 제공하기 위해서는 `.env`파일이 깃헙 리파지터리에 위치해 있어야 합니다.

원래 클라이언트에게 노출되는 값이긴 하지만, `.env` 파일을 그대로 올리는 방식 이외에,
다른 방식이 있을지 같이 해결방안을 마련할 수 있으면 좋을 것 같습니다.

**Comment by atoye1** [comment]
https://javascript.plainenglish.io/deploy-a-react-app-to-aws-s3-with-github-actions-a-step-by-step-guide-3572265332a3

https://ji5485.github.io/post/2021-06-26/create-env-with-github-actions-secrets/

위 글들을 참고해서 구현중입니다.

.env 파일에 들어가는 값은 한개인가요?
다른 경로로 .env파일 전체를 전달해주시면 좋겠습니다.

**Comment by Duhoon** [comment]
넵, 딱 한 줄 들어가게 될 거에요!
클라이언트 쪽 `.env파일`을 동헌님께 전달해달라는 말씀일까요?!

저도 위 글을 한 번 읽고 고민해보도록 하겠습니다!

**Comment by atoye1** [comment]
네 복붙해서 디코로 전달해주시면 됩니다.

**Comment by atoye1** [comment]
![image](https://user-images.githubusercontent.com/47937914/211526651-f7c46bc3-8877-4c99-b180-489a05e11bda.png)

해결되었습니니다.
