### ISSUE TITLE
[client] 로그아웃 서버 API 연동

### ISSUE THREAD

**Issue by Duhoon** [codestates-beb/beb-07-second-EWE#157]

**Comment by Duhoon** [comment]
<img width="1120" alt="스크린샷 2023-01-11 오전 12 27 59" src="https://user-images.githubusercontent.com/18072469/211594560-89830d7b-7baa-4bfe-a537-e2496c0a64b3.png">

현재 위처럼 쿠키는 잘 삭제되었다고 응답이 오는데, 실제로 클라이언트에서는 쿠키가 삭제되지 않아 새로고침을 해도 다시 재로그인 되는 상황이 발생합니다.

**Comment by atoye1** [comment]
자꾸 우리를 괴롭히는 cors cookie 문제였습니다.

아래와 같이 cookie option을 줘서 해결했습니다.
```javascript
res.clearCookie('refreshToken', {
  sameSite: 'none',
  secure: true,
  maxAge: 1,
  httpOnly: true,
});
```

제가 테스트해본 바로는 로그아웃이 잘 작동하는데, 다시 확인해보시고 이슈 닫아주시기 바랍니다.
