### ISSUE TITLE
Side Bar Modal 구현

### ISSUE THREAD

**Issue by Russ481-k** [codestates-beb/beb-07-second-EWE#162]
토큰 전송과 NFT 거래를 위한 SideBar 구성

NFT거래
매수자가 NFT 선정
NFT owner에게 가격제시
-nft address
-owner wallet address
-price

NFT owner는 가격을 수락 혹은 거절

수락 시 
해당 가격에서 수수료가 제외된 토큰이 owner에게 전송
매수자(recipent)에게 NFT 전송

거절 시 
매수자에게 미체결 통보

**Comment by Duhoon** [comment]
사이드바 스크롤 락 버그 수정해주셔야 합니다!

**Comment by Duhoon** [comment]
로그인 이후 스크롤 락 걸리는 문제가 있습니다.

**Comment by Russ481-k** [comment]
해당 확인 후 수정 했습니다.
트랜잭션 후 사용자에게 메시지를 주는 공간을 만들어 놨습니다.

**Comment by atoye1** [comment]
![image](https://user-images.githubusercontent.com/47937914/212070966-2bc88b4b-98da-4c07-9a47-7e7127606827.png)
사이드바에서 잔액이 정상적으로 표시되지 않는 버그를 발견했습니다.

**Comment by Russ481-k** [comment]
수정하여 커밋 했습니다.

**Comment by Russ481-k** [comment]
완료하여 이슈를 닫습니다!
