### ISSUE TITLE
[server]유저간 erc20 토큰전송 api 구현

### ISSUE THREAD

**Issue by atoye1** [codestates-beb/beb-07-second-EWE#173]

**Comment by atoye1** [comment]
토큰 전송을 POST 요청으로 받으려고 합니다.

배포된 클라이언트를 보니 토큰전송시 주소값을 입력으로 받던데
주소값 말고 아래와 같이 user 테이블의 PK인 email을 POST요청의 입력으로 받았으면 하는데 괜찮을지 답글 달아주세요.
참고로 amount도 스트링으로 받습니다.

{
	"email":"test1@test.com"
	"amount":"10000000"
}

**Comment by Duhoon** [comment]
구현상으로는 문제가 없는데 웹3적인 느낌은 안 든 다는게 흠이네요.
상관 없을 것 같습니다.

**Comment by atoye1** [comment]
클라이언트에서 다른 유저의 주소값을 볼 수 있다면 주소로 받아도 괜찮습니다.

**Comment by Duhoon** [comment]
넵, 클라이언트는 포스트 디테일 페이지에서 리뷰를 작성한 글쓴이의 주소값을 확인하고, 해당 주소값을 복사하여 토큰 전송 UI에 붙여넣기 할 수 있을 정도의 UI를 제공하려고 합니다.

현재 서버에 포스트 하나의 데이터를 요청하면 작성자의 지갑 주소값까지 반환되는 것 확인되었습니다.

이렇게 구현되면 아마 문제 없을 것 같네요!

**Comment by atoye1** [comment]
그럼 address랑 amount를 받는걸로 작성하겠습니다.

**Comment by Duhoon** [comment]
확인됐습니다.

**Comment by atoye1** [comment]
### api uri

POST /token/transfer

### success example
![image](https://user-images.githubusercontent.com/47937914/211712197-7154dd00-ac43-4d07-a17a-2f6fb5f29124.png)

### error example
![image](https://user-images.githubusercontent.com/47937914/211712091-e0924506-14f7-4876-ade8-5173ff0dda3f.png)

**Comment by Duhoon** [comment]
혹시 요청 보낼 때 클라이언트에서 보내는 데이터에는 `누가 누구에게 토큰 몇 개 전송한다`에서 `누가`에 대한 정보는 없어도 될까요?!

누구(address)에게 토큰 몇 개(amount)에 대한 정보만 보내도 정상적으로 요청한 유저에게서 토큰이 빠져나가는 지 여쭤보고 싶습니다.

**Comment by atoye1** [comment]
로그인된 유저가 자신의 계정에서만 보내기 때문에 누가는 없어도 괜찮습니다.

**Comment by Duhoon** [comment]
서버에서 자체적으로 로그인 유저를 판별하는 로직이 짜여져 있군요!
알겠습니다.
