### ISSUE TITLE
[server] 게시글 수정, 마이페이지 수정 API 작성

### ISSUE THREAD

**Issue by hyuntae384** [codestates-beb/beb-07-second-EWE#174]

**Comment by Duhoon** [comment]
클라이언트 쪽에서도 우선은 막아놓을 건데,
서버 쪽에서도 게시글 수정하는 유저, 마이페이지 프로필 수정하려는 유저가 권한이 있는지 체크하는 로직이 필요할 것 같습니다.

**Comment by hyuntae384** [comment]
권한 체크 로직까지 구현 완료
