### ISSUE TITLE
[client] 사용자간 토큰 전송 기능 제공

### ISSUE THREAD

**Issue by Duhoon** [codestates-beb/beb-07-second-EWE#178]
커뮤니티 이용자들간에 활동으로 얻은 토큰을 서로 교환할 수 있는 기능을 제공합니다.

**Comment by Duhoon** [comment]
401 에러가 뜨는 현상 해결하다가 Header의 Authorization에 accessToken을 같이 보내면 해결된다는 것을 깨달았습니다.
수정하고 작동하는지 확인한 뒤에 이슈 닫겠습니다.

**Comment by Duhoon** [comment]
2번 입력되는 문제 상황 파악되어 정상 작동하는 걸로 간주하고 이슈 닫도록 하겠습니다.

**Comment by Duhoon** [comment]
현재 토큰 전송 시 성공이라고 응답 받아오는데, 실질적으로 반영은 하고 있지 않은 것 같습니다.
포스트맨으로도 확인해보는데, 응답은 성공적으로 반영되었다하고 실제 잔고 변경은 없는 것으로 보입니다.

**Comment by atoye1** [comment]
문제가 있음을 확인하고, 고친 코드를 배포중입니다.
비동기로 web3 트랜잭션을 처리하여 요청의 완료까지 기다리지 않고 즉시response를 반환하므로
관련 에러메시지를 클라이언트에서 볼 수 없다는 단점이 있네요. 디버깅도 더 까다로워 졌습니다.

서버 재배포하고 테스트 후에 이슈를 닫겠습니다.
