### ISSUE TITLE
[server]시퀄라이즈와 DB 서버 연동

### ISSUE THREAD

**Issue by hyuntae384** [codestates-beb/beb-07-second-EWE#18]
1. 시퀄라이즈, 시퀄라이즈 cli 활용법을 익힌다.
2. db 스키마를 보고 모델코드를 작성한다.
3. express 서버 실행시 db와 연결하는 코드를 작성한다
4. seeder를 활용해서 최초 데이터를 삽입한다.

**Comment by hyuntae384** [comment]
config.json 파일에 username과 password 부분을 env 파일로 작성해서 사용해야할까요?

**Comment by atoye1** [comment]
일단 하드코딩해서 테스트하시고 잘 작동하면 .env로 관리하는게 디버그하기 편하실것 같아요

**Comment by hyuntae384** [comment]
model:generate을 하고 나서 해당 model파일에서 스키마를 수정하면 migrate시에 반영이 안되는데 수정할 수 있는 방법이 있을까요?

**Comment by atoye1** [comment]
음 .. 이렇게 말해주시면 제가 무슨상황인이 이해하기 어려워서,

전후 맥락이랑 명령어, 문제가 있다고 생각하는 코드, 에러메시지를 다 알려주시면 좋을 것 같아요.

**Comment by hyuntae384** [comment]
아 넵 제가 migrate 같은 상황이 발생하면 에러메시지를 보여드리겠습니다.

혹시 더미데이터에 images 같은 경우는 데이터 타입을 뭐로 해야할까요..?

**Comment by atoye1** [comment]
원래는 이미지 테이블을 두고 왜래키로 관리해야할것 같지만
일단 편의를 위해서 스트링이나 varchar 타입으로 할게요. 한 1000글자 이상 정도 들어갈 수 있는 데이터 타입이면 괜찮을것 같아요.

**Comment by hyuntae384** [comment]
스키마를 노션에 'DB설계' 부분에 있는 스키마 캡쳐본대로 하고, 더미데이터에 없는 값들은 null로 표시되게 하면 될까요?
