### ISSUE TITLE
[demo] 데모 테스트 시나리오

### ISSUE THREAD

**Issue by Duhoon** [codestates-beb/beb-07-second-EWE#265]
데모 테스트를 진행해보려고 합니다. 다음 테스트 중 맘에 드는 것 아무거나 골라 테스트를 해보고 모든 기능 잘 작동하는 지 확인해보세요!
하면서 영상이나 GIF를 찍어두면 블로깅에도 도움이 될 겁니다~!

# 테스트1
회원가입 -> NFT 민팅 -> NFT 민팅(토큰 없어서 안됨) -> 포스팅 -> 작성된 리뷰 보기 -> 토큰 7개 보내기

# 테스트2
로그인 -> 포스팅 -> 포스팅 -> 작성된 리뷰 보기 -> 마음에 드는 포스팅 작성자에게 토큰 7 개 보내기

# 테스트3
회원가입 -> 로그아웃 -> 로그인 -> 작성된 리뷰보기 -> 포스팅 작성자에게 토큰 7 개 보내기 -> NFT 민팅 -> 작성된 리뷰보기

# 테스트4
로그인 -> 작성된 리뷰보기 -> 토큰 7개 보내기 -> NFT 민팅 -> 작성된 리뷰 보기 -> 포스팅하기

**Comment by atoye1** [comment]
2번 시나리오 테스트 했습니다.
포스팅시 정적 이미지 대신 GIF를 올려도 정상적으로 작동하는걸 확인했습니다.

**Comment by Russ481-k** [comment]
4번 시나리오 진행 해 볼게요

**Comment by Russ481-k** [comment]
4번 시나리오도 테스트 잘 되는 것 확인 했습니다.

**Comment by Duhoon** [comment]
3번 시나리오를 테스트하고 있는데, NFT 민팅이 리다이렉트 될 때까지 시간이 조금 걸립니다. 아직 해당 UX는 제공이 되고 있지 않아서 민팅할 정지된 화면을 보게 될 것 같습니다.
