### ISSUE TITLE
헤더

### ISSUE THREAD

**Issue by Russ481-k** [codestates-beb/beb-07-second-EWE#39]
-헤더에서 메인 페이지, 마켓페이지, 마이페이지로 접근 할 수 있음
 -헤더에서 로그인 되었을 경우 닉네임과 로그아웃 버튼이 생김 
-헤더에서 로그인을 하지 않거나 로그아웃 되었을 경우 ID PW란과 로그인 및 회원가입 버튼이 있음 
-헤더에서 ETH Faucet 버튼을 사용할 수 있음

**Comment by Duhoon** [comment]
구현 완료되어 이슈 닫도록 하겠습니다.
