### ISSUE TITLE
[server] 서버 API 구현

### ISSUE THREAD

**Issue by hyuntae384** [codestates-beb/beb-07-second-EWE#47]
DB 데이터 GET, POST, PUT 정상 작동 구현

**Comment by Duhoon** [comment]
GET `/posts/:postId` 로  포스트 하나에 대한 요청을 할 때, 혹 아직 데이터베이스에 없는 포스트ID를 조회하려고 하는 유저에 대한 예외처리를 하려고 합니다.

이 때 서버에서 받는 응답 Status 값은 500으로 받고 있는데, 데이터베이스를 조회하는 쿼리는 잘 작동한다면 `404`로 반환 할 수 있게 수정 부탁 드리겠습니다.
