### ISSUE TITLE
[server] DB posts테이블 테스트 데이터 추가 생성

### ISSUE THREAD

**Issue by hyuntae384** [codestates-beb/beb-07-second-EWE#56]

**Comment by hyuntae384** [comment]
posts 더미데이터 15개 추가. 총 20개
images 더미데이터 16개 추가. 총 21개
(1번 포스트에 이미지 2개 표시를 위한 이미지 더미데이터 1개)

**Comment by atoye1** [comment]
http://20.214.190.113:5050/testv2/posts
