### ISSUE TITLE
[client] NFT Component 구현

### ISSUE THREAD

**Issue by Russ481-k** [codestates-beb/beb-07-second-EWE#63]
여러 페이지에 출력될 NFT component 구현
주어진 데이터
- tokenID
- owner (FK)
- ContractAccount
- createdAt
- owner
- creator
- listed
- price
- transactions[]

요구 데이터
- tokenID
- createdAt
- creator
- price
- owner

**Comment by Russ481-k** [comment]
nfts로 넘어오는 데이터에 image가 metadata의 json 주소에 있는 images의 key값인 걸 확인 했으나 그 데이터를 읽어 오는데 어려움이 있습니다.

**Comment by atoye1** [comment]
오류메시지도 같이 올려주시면 함께 해결하는데 더 도움이 될것같습니다.

**Comment by Duhoon** [comment]
해당 부분 구현, 제가 이양받아서 확인 중에 있습니다.
다시 한 번 체크하고 에러메시지 공유하도록 하겠습니다.
늦게 답변 드리게되어서 죄송합니다!

**Comment by Duhoon** [comment]
**[로컬 클라이언트 앱에서의 JSON 요청 에러]**
<img width="739" alt="스크린샷 2023-01-07 오후 11 08 13" src="https://user-images.githubusercontent.com/18072469/211155027-0bb7067a-29c6-42a7-a684-221e28099954.png">

**[호스팅 클라이언트 앱에서의 JSON 요청 에러]**

<img width="739" alt="스크린샷 2023-01-07 오후 11 25 03" src="https://user-images.githubusercontent.com/18072469/211155558-3a19d5c7-818a-4fb4-a367-89c807d57434.png">



현재 서버에서 제공해주는 `/testv2/nfts` API를 통해서 NFT 정보들을 가져오고 있습니다.
그리고 metadata 컬럼에서 확인할 수 있는 S3의 JSON 파일 URL로 GET 요청을 했을 때 위와 같은 문제가 발생합니다.
아마 현재 NFT 메타데이터인 JSON 파일이 저장된 S3 버킷의 CORS 정책이 현재 클라이언트가 사용하고 있는 `origin`을 허용해주지 않고 있어서 발생하는 문제인 것 같아서, CORS 정책을 변경해주시면 좋을 것 같습니다.

`http://localhost:3000` 과 `http://ewe-client.s3-website.ap-northeast-2.amazonaws.com/`을 허용해주시면 될 것 같아요.

보안상의 문제가 우려되지 않는다면, 이번 프로젝트 개발 동안만 `Access-Contorll-Allow-Origin`을 `*`로 설정해주셔도 좋을 것 같습니다.

**Comment by atoye1** [comment]
![image](https://user-images.githubusercontent.com/47937914/211156227-c0c033c4-6423-441f-9f98-8e723bf417b0.png)
버킷 정책을 수정했는데 잘 작동하는지 확인해주시겠어요?

**Comment by Duhoon** [comment]
<img width="739" alt="스크린샷 2023-01-07 오후 11 42 56" src="https://user-images.githubusercontent.com/18072469/211156374-a248c092-7e84-4f20-9269-97d35e0314bd.png">

GET 요청으로 JSON 메타데이터 잘 받아와지는 것 확인했습니다.
감사합니다!
