### ISSUE TITLE
[server]user 테이블 erc20, eth 컬럼 데이터타입 변경

### ISSUE THREAD

**Issue by atoye1** [codestates-beb/beb-07-second-EWE#85]

**Comment by atoye1** [comment]
![Image](https://user-images.githubusercontent.com/47937914/210928691-6bb1b6ee-e1ac-4a6e-a536-d4b064a72f21.png)

계정내 이더와 토큰 잔액이 일반적인 int보다 단위가 커서
정상적으로 들어가지 않는 이슈가 발생했습니다.

user테이블의 해당 컬럼(erc20, eth) 타입을 String으로 변경 요청합니다.

**Comment by hyuntae384** [comment]
model수정과 migration을 통해 변경 완료하였습니다.
